:man source:   Yabai
:man version:  {revnumber}
:man manual:   Yabai Manual

yabai(1)
========

Name
----

yabai

Synopsis
--------

*yabai* [*-v*,*--version*|*-V*,*--verbose*|*-m*,*--message* 'msg'|*-c*,*--config* 'config_file'|*--install-sa*|*--uninstall-sa*|*--load-sa*]

Description
-----------

*yabai* is a tiling window manager for macOS based on binary space partitioning.

Options
-------
*-v*, *--version*::
    Print the version and exit.

*-V*, *--verbose*::
    Output debug information to stdout.

*-m*, *--message* '<msg>'::
    Send message to a running instance of yabai.

*-c*, *--config* '<config_file>'::
    Use the specified configuration file.

*--install-sa*::
    Install the scripting-addition into /System/Library/ScriptingAdditions. Must be ran as root.

*--uninstall-sa*::
    Remove the scripting-addition from /System/Library/ScriptingAdditions. Must be ran as root.

*--load-sa*::
    Loads the scripting-addition into Dock.app.

Definitions
-----------

----
DIR_SEL     := north | east | south | west

DISPLAY_SEL := prev | next | last | arrangement index (1-based)

SPACE_SEL   := prev | next | last | mission-control index (1-based)
----

Domains
-------

Config
~~~~~~

General Syntax
^^^^^^^^^^^^^^

yabai -m config [--space '<mission-control index>'] <setting> [<value>]::
    Get or set the value of <setting>.

Global Settings
^^^^^^^^^^^^^^^

Colors are in the form '#AARRGGBB', booleans are 'on' or 'off'.

'mouse_follows_focus'::
    When focusing a window, put the mouse at its center.

'focus_follows_mouse'::
    Focus the window under the mouse. Accept the following values: *autofocus*, *autoraise*, *off*.

'window_shadow'::
    Draw shadow for windows. Accept the following values: *on*, *float*, *off*.

'window_border'::
    Draw border for windows.

'window_border_width'::
    Width of window borders.

'active_window_border_color'::
    Color of the border of the focused window.

'normal_window_border_color'::
    Color of the border of an unfocused window.

'insert_window_border_color'::
    Color of the *window --insert* message selection.

'active_window_opacity'::
    Opacity of the focused window.

'normal_window_opacity'::
    Opacity of an unfocused window.

'split_ratio'::
    Default split ratio.

'auto_balance'::
    Balance the window tree upon change, so that all windows occupy the same area.

'mouse_modifier'::
    Keyboard modifier used for moving and resizing windows. Accept the following values: *cmd*, *alt*, *shift*, *ctrl*, *fn*.

'mouse_action1'::
'mouse_action2'::
    Action performed when pressing 'mouse_modifier' + 'button<n>'. Accept the following values: *move*, *resize*.

Space Settings
^^^^^^^^^^^^^^

'layout'::
    Set the layout of the selected space. Accept the following values: *bsp*, *float*.

'top_padding'::
'bottom_padding'::
'left_padding'::
'right_padding'::
    Padding added at the sides of the selected space.

'window_gap'::
    Size of the gap that separates windows for the selected space.

Display
~~~~~~~

General Syntax
^^^^^^^^^^^^^^

yabai -m display 'COMMAND'

COMMAND
^^^^^^^

*--focus* 'DISPLAY_SEL'::
    Focus the given display.

Space
~~~~~

General Syntax
^^^^^^^^^^^^^^

yabai -m space 'COMMAND'

COMMAND
^^^^^^^

*--focus* 'SPACE_SEL'::
    Focus the given space.

*--move* 'DISPLAY_SEL'::
    Move the active space to the given display.

*--create*::
    Create a new space on the active display.

*--destroy*::
    Remove the currently active space.

*--balance*::
    Adjust the split ratios of the active space so that all windows occupy the same area.

*--mirror* 'x-axis|y-axis'::
    Flip the tree of the active space.

*--rotate* '90|180|270'::
    Rotate the tree of the active space.

*--padding* '<top>:<bottom>:<left>:<right>'::
    Padding added at the sides of the space.

*--gap* '<gap>'::
    Size of the gap that separates windows.

*--toggle* 'padding|gap'::
    Toggle space setting on or off.

*--layout* 'bsp|float'::
    Set the layout of the space.

Window
~~~~~~

General Syntax
^^^^^^^^^^^^^^

yabai -m window 'COMMAND'

COMMAND
^^^^^^^

*--focus* 'DIR_SEL'::
    Focus the window in the given direction.

*--swap* 'DIR_SEL'::
    Swap position with the window in the given direction.

*--warp* 'DIR_SEL'::
    Re-insert, splitting the window in the given direction.

*--insert* 'DIR_SEL'::
    Select the splitting area of the focused window. If the current selection matches 'DIR_SEL', the action will be undone.

*--grid* '<rows>:<cols>:<start-x>:<start-y>:<width>:<height>'::
    Set the window frame based on a self-defined grid.

*--move* '<dx>:<dy>'::
    Move window by 'dx' pixels horizontally and 'dy' pixels vertically.

*--resize* 'top|left|bottom|right|top_left|top_right|bottom_right|bottom_left:<dx>:<dy>'::
    Resize window by moving the given handle 'dx' pixels horizontally and 'dy' pixels vertically.

*--toggle* 'float|sticky|split|border|fullscreen|native-fullscreen'::
    Toggle the selected property of a window.

*--display* 'DISPLAY_SEL'::
    Send the window to the given display.

*--space* 'SPACE_SEL'::
    Send the window to the given space.

Query
~~~~~~

General Syntax
^^^^^^^^^^^^^^

yabai -m query 'COMMAND' ['ARGUMENT']

COMMAND
^^^^^^^

*--displays*::
    Retrieve information about displays.

*--spaces*::
    Retrieve information about spaces.

*--windows*::
    Retrieve information about windows.

ARGUMENT
^^^^^^^^

*--display* ['<arrangement index']::
    Constrain matches to the selected display.

*--space* ['<mission-control index>']::
    Constrain matches to the selected space.

*--window*::
    Constrain matches to the focused window.

Exit Codes
----------

If *yabai* can't handle a message, it will return a non-zero exit code.

Author
------

Åsmund Vikane <aasvi93 at gmail.com>
