:man source:   Yabai
:man version:  {revnumber}
:man manual:   Yabai Manual

ifdef::env-github[]
:toc:
:toc-title:
:toc-placement!:
:numbered:
endif::[]

yabai(1)
========

ifdef::env-github[]
toc::[]
endif::[]

Name
----

yabai

Synopsis
--------

*yabai* [*-v*,*--version*|*-V*,*--verbose*|*-m*,*--message* 'msg'|*-c*,*--config* 'config_file'|*--install-sa*|*--uninstall-sa*|*--load-sa*]

Description
-----------

*yabai* is a tiling window manager for macOS based on binary space partitioning.

Options
-------
*-v*, *--version*::
    Print the version and exit.

*-V*, *--verbose*::
    Output debug information to stdout.

*-m*, *--message* '<msg>'::
    Send message to a running instance of yabai.

*-c*, *--config* '<config_file>'::
    Use the specified configuration file.

*--install-sa*::
    Install the scripting-addition into /System/Library/ScriptingAdditions. Must be ran as root.

*--uninstall-sa*::
    Remove the scripting-addition from /System/Library/ScriptingAdditions. Must be ran as root.

*--load-sa*::
    Loads the scripting-addition into Dock.app.

Definitions
-----------

[subs=+macros]
----
DIR_SEL     := north | east | south | west

WINDOW_SEL  := prev | next | last | DIR_SEL

DISPLAY_SEL := prev | next | last | arrangement index (1-based)

SPACE_SEL   := prev | next | last | mission-control index (1-based)

FLOAT_SEL   := 0 < value <= 1.0

BOOL_SEL    := on | off

REGEX       := https://www.gnu.org/software/findutils/manual/html_node/find_html/posix_002dextended-regular-expression-syntax.html[POSIX extended regular expression syntax]
----

Domains
-------

Config
~~~~~~

General Syntax
^^^^^^^^^^^^^^

yabai -m config [--space '<mission-control index>'] <setting> [<value>]::
    Get or set the value of <setting>.

Global Settings
^^^^^^^^^^^^^^^

Colors are in the form '#AARRGGBB'.

'status_bar'::
    Enable custom status bar.

'status_bar_font_family'::
    Specify name of font family to use for drawing text. Use 'Font Book.app' to identify the correct name.

'status_bar_icon_font_family'::
    Specify name of font family to use for drawing icon symbols, typically FontAwesome. Use 'Font Book.app' to identify the correct name.

'status_bar_background_color'::
    Color to use for drawing status bar background.

'status_bar_foreground_color'::
    Color to use for drawing status bar elements.

'status_bar_space_icon_strip'::
    Specify symbols separated by whitespace to be used for visualizing spaces.

'status_bar_power_icon_strip'::
    Specify two symbols separated by whitespace. The first symbol represents battery power and the second symbol indicates AC.

'status_bar_space_icon'::
    Specify a general symbol to use for any given space that does not have a match in 'status_bar_space_icon_strip'.

'status_bar_clock_icon'::
    Specify a symbol to represent the current time.

'mouse_follows_focus'::
    When focusing a window, put the mouse at its center.

'focus_follows_mouse'::
    Focus the window under the mouse. Accept the following values: *autofocus*, *autoraise*, *off*.

'window_topmost'::
    Make floating windows stay on top.

'window_opacity'::
    Enable opacity for windows.

'window_shadow'::
    Draw shadow for windows. Accept the following values: *on*, *float*, *off*.

'window_border'::
    Draw border for windows.

'window_border_width'::
    Width of window borders.

'active_window_border_color'::
    Color of the border of the focused window.

'normal_window_border_color'::
    Color of the border of an unfocused window.

'insert_window_border_color'::
    Color of the *window --insert* message selection.

'active_window_opacity'::
    Opacity of the focused window.

'normal_window_opacity'::
    Opacity of an unfocused window.

'split_ratio'::
    Default split ratio.

'auto_balance'::
    Balance the window tree upon change, so that all windows occupy the same area.

'mouse_modifier'::
    Keyboard modifier used for moving and resizing windows. Accept the following values: *cmd*, *alt*, *shift*, *ctrl*, *fn*.

'mouse_action1'::
'mouse_action2'::
    Action performed when pressing 'mouse_modifier' + 'button<n>'. Accept the following values: *move*, *resize*.

Space Settings
^^^^^^^^^^^^^^

'layout'::
    Set the layout of the selected space. Accept the following values: *bsp*, *float*.

'top_padding'::
'bottom_padding'::
'left_padding'::
'right_padding'::
    Padding added at the sides of the selected space.

'window_gap'::
    Size of the gap that separates windows for the selected space.

Display
~~~~~~~

General Syntax
^^^^^^^^^^^^^^

yabai -m display '<COMMAND>'

COMMAND
^^^^^^^

*--focus* '<DISPLAY_SEL>'::
    Focus the given display.

Space
~~~~~

General Syntax
^^^^^^^^^^^^^^

yabai -m space '<COMMAND>'

COMMAND
^^^^^^^

*--focus* '<SPACE_SEL>'::
    Focus the given space.

*--create*::
    Create a new space on the active display.

*--destroy*::
    Remove the currently active space.

*--move* 'prev|next'::
    Swap position of the active space with the prev/next space.

*--display* '<DISPLAY_SEL>'::
    Send the active space to the given display.

*--balance*::
    Adjust the split ratios of the active space so that all windows occupy the same area.

*--mirror* 'x-axis|y-axis'::
    Flip the tree of the active space.

*--rotate* '90|180|270'::
    Rotate the tree of the active space.

*--padding* '<top>:<bottom>:<left>:<right>'::
    Padding added at the sides of the space.

*--gap* '<gap>'::
    Size of the gap that separates windows.

*--toggle* 'padding|gap'::
    Toggle space setting on or off.

*--layout* 'bsp|float'::
    Set the layout of the space.

Window
~~~~~~

General Syntax
^^^^^^^^^^^^^^

yabai -m window '<COMMAND>'

COMMAND
^^^^^^^

*--focus* '<WINDOW_SEL>'::
    Focus the window in the given direction.

*--swap* '<WINDOW_SEL>'::
    Swap position with the window in the given direction.

*--warp* '<WINDOW_SEL>'::
    Re-insert, splitting the window in the given direction.

*--insert* '<DIR_SEL>'::
    Select the splitting area of the focused window. If the current selection matches 'DIR_SEL', the action will be undone.

*--grid* '<rows>:<cols>:<start-x>:<start-y>:<width>:<height>'::
    Set the window frame based on a self-defined grid.

*--move* '<dx>:<dy>'::
    Move window by 'dx' pixels horizontally and 'dy' pixels vertically.

*--resize* 'top|left|bottom|right|top_left|top_right|bottom_right|bottom_left:<dx>:<dy>'::
    Resize window by moving the given handle 'dx' pixels horizontally and 'dy' pixels vertically.

*--toggle* 'float|sticky|split|border|fullscreen|native-fullscreen'::
    Toggle the selected property of a window.

*--display* '<DISPLAY_SEL>'::
    Send the window to the given display.

*--space* '<SPACE_SEL>'::
    Send the window to the given space.

Query
~~~~~~

General Syntax
^^^^^^^^^^^^^^

yabai -m query '<COMMAND>' ['<ARGUMENT>']

COMMAND
^^^^^^^

*--displays*::
    Retrieve information about displays.

*--spaces*::
    Retrieve information about spaces.

*--windows*::
    Retrieve information about windows.

ARGUMENT
^^^^^^^^

*--display* ['<arrangement index']::
    Constrain matches to the selected display.

*--space* ['<mission-control index>']::
    Constrain matches to the selected space.

*--window*::
    Constrain matches to the focused window.

Rule
~~~~

General Syntax
^^^^^^^^^^^^^^

yabai -m rule '<COMMAND>' ['<ARGUMENT>']

COMMAND
^^^^^^^

*--add*::
    Add a new rule.

ARGUMENT
^^^^^^^^

*app='<REGEX>'*::
    Name of application.

*title='<REGEX>'*::
    Title of window.

*display='[^]<arrangement index>'*::
    Send window to display. If '^' is present, follow focus.

*space='[^]<mission-control index>'*::
    Send window to space. If '^' is present, follow focus.

*opacity='<FLOAT_SEL>'*::
    Set window opacity.

*manage='<BOOL_SEL>'*::
    Window should be managed (tile vs float)

*sticky='<BOOL_SEL>'*::
    Window appears on all spaces.

*border='<BOOL_SEL>'*::
    Window should draw border.

*native-fullscreen='<BOOL_SEL>'*::
    Window should enter native macOS fullscreen mode.

*grid='<rows>:<cols>:<start-x>:<start-y>:<width>:<height>'*::
    Set window frame based on a self-defined grid.

Signal
~~~~~~

A signal is a simple way for the user to react to some event that has been processed.

General Syntax
^^^^^^^^^^^^^^

yabai -m signal '<COMMAND>' event='<EVENT>' action='<ACTION>'

COMMAND
^^^^^^^

*--add*::
    Add a new signal to execute an action after processing an event of the given type.

EVENT
^^^^^

*application_launched*::
    Triggered when a new application is launched. Passes one argument: pid

*application_terminated*::
    Triggered when an application is terminated. Passes one argument: pid

*application_front_switched*::
    Triggered when the front-most application changes. Passes two arguments: front_pid, last_front_pid

*application_activated*::
    Triggered when an application is activated. Passes one argument: pid

*application_deactivated*::
    Triggered when an application is deactivated. Passes one argument: pid

*application_visible*::
    Triggered when an application is unhidden. Passes one argument: pid

*application_hidden*::
    Triggered when an application is hidden. Passes one argument: pid

*window_created*::
    Triggered when a window is created. Passes two arguments: pid, wid

*window_destroyed*::
    Triggered when a window is destroyed. Passes two arguments: pid, wid

*window_focused*::
    Triggered when a window becomes the key-window for its application. Passes two arguments: pid, wid

*window_moved*::
    Triggered when a window changes position. Passes two arguments: pid, wid

*window_resized*::
    Triggered when a window changes dimensions. Passes two arguments: pid, wid

*window_minimized*::
    Triggered when a window has been minimized. Passes two arguments: pid, wid

*window_deminimized*::
    Triggered when a window has been deminimized. Passes two arguments: pid, wid

*window_title_changed*::
    Triggered when a window changes its title. Passes two arguments: pid, wid

*space_changed*::
    Triggered when the active space has changed. Passes two arguments: space_id, last_space_id

*display_added*::
    Triggered when a new display has been added. Passes one argument: display_id

*display_removed*::
    Triggered when a display has been removed. Passes one argument: display_id

*display_moved*::
    Triggered when a change has been made to display arrangement. Passes one argument: display_id

*display_resized*::
    Triggered when a display has changed resolution. Passes one argument: display_id

*display_changed*::
    Triggered when the active display has changed. Passes two arguments: display_id, last_display_id

*mouse_down*::
    Triggered when a mouse button has been pressed. Passes two arguments: button, coordinates

*mouse_up*::
    Triggered when a mouse button has been released. Passes two arguments: button, coordinates

*mouse_dragged*::
    Triggered when the mouse is moved with one of its buttons pressed. Passes two arguments: button, coordinates

*mouse_moved*::
    Triggered when the mouse is moved. Passes two arguments: button, coordinates

*mission_control_enter*::
    Triggered when mission-control activates.

*mission_control_check_for_exit*::
    Triggered periodically while mission-control is active.

*mission_control_exit*::
    Triggered when mission-control deactivates.

*dock_did_restart*::
    Triggered when Dock.app restarts.

*menu_opened*::
    Triggered when a menu is opened.

*menu_bar_hidden_changed*::
    Triggered when the macOS menubar 'autohide' setting changes.

*system_woke*::
    Triggered when macOS wakes from sleep.

*bar_refresh*::
    Triggered when the yabai status_bar is told to update.

*daemon_message*::
    Triggered when yabai receives a message on its socket.

ACTION
^^^^^^

Arbitrary command executed through */usr/bin/env sh -c*

Exit Codes
----------

If *yabai* can't handle a message, it will return a non-zero exit code.

Author
------

Åsmund Vikane <aasvi93 at gmail.com>
